### PR TITLE
add geometric rois.

### PR DESCRIPTION
**Pull request by seebacherd**
I've created some simple two-dimensional ROIs, for example a Polygon or the Rasterized Version of the Polygon. Tests for the newly implemented ROIS can be found in src/test/java/net/imglib2/roi/geometric/GeometricROITest.java.

I've created a little diagram to give an overview of the implementation.
overview

### CODE REVIEW

**Comment by DanielSeebacher** [comment]
@tpietzsch, any plans when you can review this?

**Comment by tpietzsch** [comment]
@DanielSeebacher it may take a few days until I can look at it in depth. But thanks for pinging me! Somehow, I had missed this PR originally. It's on the agenda now.

**Comment by DanielSeebacher** [comment]
@tpietzsch, any updates? Did you have time to look at it?

**Comment by tpietzsch** [comment]
sorry, no not yet.

**Comment by DanielSeebacher** [comment]
@tpietzsch  any news?

**Comment by dietzc** [comment]
I talked to @tpietzsch  and we decided we will take a look at this PR during the next hackathon@madison.

**Comment by tpietzsch** [comment]
this is superseded by https://github.com/imglib/imglib2-roi/pull/17
We will come back to the scanline rasterization in `RasterizedPolygon` later. In https://github.com/imglib/imglib2-roi/pull/17 this is done very straightforward (i.e., slow). Before we use scanline rasterization, we need to make sure that it yields the same results as the straightforward method.

**Pull request closed without merging**
