### PR TITLE
Added n-dimensional elipsoid and rectangle ROIs, as well as binary operations for ROIs (union, intersection,...)

### PR DESCRIPTION
**Pull request by haesleinhuepf**

### CODE REVIEW

**Comment by ctrueden** [comment]
I would suggest massaging the history a bit to clean things. But this looks like an awesome direction! Nice work!

**Comment by acardona** [comment]
Question @haesleinhuepf : ImgLib2 already has an n-dimensional ellipse roi, by @LeeKamentsky : https://github.com/imglib/imglib2-roi/blob/master/src/main/java/net/imglib2/roi/EllipseRegionOfInterest.java

Is the new one different in some way?

**Comment by haesleinhuepf** [comment]
Yes it is. The new one is compatible with the Polygon class in the same folder. I talked to @tpietzsch and found out that the class you mentioned was marked as deprecated because it does not implement the interfaces RealRandomAccessibleRealInterval< BoolType > and Contains< RealLocalizable >. But all geometric structures should have these interfaces to make them uniformly usable.

**Comment by acardona** [comment]
@haesleinhuepf Sounds great. Thanks for your contribution!

**Comment by haesleinhuepf** [comment]
I recreated the pull request with a rewritten history

**Pull request closed without merging**
